import { useState } from "react"
import Head from "next/head"
import Image from "next/image"
import { FiChevronDown } from "react-icons/fi"
import dms from "../../public/digital-media-strategy.webp"
import content from "../../public/content-marketing.webp"
import advertising from "../../public/targeting.webp"
import adEngineering from "../../public/ad-engineering.webp"
import { LongText } from "../../utils"
import Link from "next/link"

const Services = () => {
  const [tab, setTab] = useState(0)

  return (
    <div>
      <Head>
        <title>The TKBrown Co. | Services</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/logo_transparent_background_small.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/logo_transparent_background_small.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/logo_transparent_background_small.png"
        />
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>

      <header className="relative h-screen bg-purple-900">
        {/**jumbo */}
        <div className="px-8 py-40 h-full font-bold text-white text-center flex items-center justify-center font-oswald">
          <span className="xl:text-9xl md:text-7xl text-3xl font-semibold">
            SERVICES
          </span>
        </div>

        {/**down button */}
        <div className="absolute bottom-6 left-1/2 text-white">
          <FiChevronDown
            size={24}
            onClick={() => {
              const height = document.documentElement.clientHeight - 125
              window.scrollTo({
                top: height,
                left: 0,
                behavior: "smooth",
              })
            }}
            className="cursor-pointer hover:-translate-y-1/4 transform transition"
          />
        </div>
      </header>

      {/**all services */}
      <div className="py-24 xl:px-32 md:px-16 px-8 flex lg:flex-row flex-col">
        <div className="lg:w-1/4 md:w-1/2 w-full lg:mb-0 mb-8 px-4">
          <div className="px-8 py-8 rounded-2xl border border-gray-50 shadow-outline shadow-gray-200 divide-y-2 divide-gray-100 space-y-4">
            <p className="text-xl font-semibold">OUR SERVICES</p>
            <div className="space-y-4 py-4 flex flex-col">
              <span
                className="cursor-pointer hover:text-purple-400 text-sm"
                onClick={() => setTab(0)}
              >
                All Services
              </span>
              <span
                className="cursor-pointer hover:text-purple-400 text-sm"
                onClick={() => setTab(1)}
              >
                Media Strategy
              </span>
              <span
                className="cursor-pointer hover:text-purple-400 text-sm"
                onClick={() => setTab(2)}
              >
                Content Marketing
              </span>
              <span
                className="cursor-pointer hover:text-purple-400 text-sm"
                onClick={() => setTab(3)}
              >
                Advertising Technology
              </span>
              <span
                className="cursor-pointer hover:text-purple-400 text-sm"
                onClick={() => setTab(4)}
              >
                Digital Media Advertising
              </span>
            </div>
          </div>
        </div>

        <div className="lg:w-3/4 w-full px-4">
          <div className="px-8 rounded-2xl border border-gray-50 shadow-outline shadow-gray-200 divide-y-2 divide-gray-200">
            {tab === 0 || tab === 1 ? (
              <div className="py-8">
                <p className="lg:text-4xl md:text-3xl text-2xl font-semibold">
                  Media Strategy
                </p>
                <div className="my-8 w-full h-96 relative">
                  <Image
                    src={dms}
                    alt="Media Strategy"
                    objectFit="contain"
                    layout="fill"
                  />
                </div>
                <p className="md:text-base text-xs">
                  Through a unique combination of media expertise, we create and
                  optimise media experiences that connect people to brands and
                  offer the best strategy for growth and expansion.
                </p>
              </div>
            ) : null}

            {tab === 0 || tab === 2 ? (
              <div className="py-8">
                <p className="lg:text-4xl md:text-3xl text-2xl font-semibold">
                  Content Marketing
                </p>
                <div className="my-8 w-full h-96 relative">
                  <Image
                    src={content}
                    alt="Content Marketing"
                    objectFit="contain"
                    layout="fill"
                  />
                </div>
                <p className="md:text-base text-xs">
                  We have the expertise to rapidly scale your business, build a
                  stronger online reputation & brand awareness.
                </p>
              </div>
            ) : null}

            {tab === 0 || tab === 3 ? (
              <div className="py-8">
                <p className="lg:text-4xl md:text-3xl text-2xl font-semibold">
                  Advertising Technology
                </p>
                <div className="my-8 w-full h-96 relative">
                  <Image
                    src={adEngineering}
                    alt="Advertising Technology"
                    objectFit="contain"
                    layout="fill"
                  />
                </div>
                <div>
                  <p className="md:text-base text-xs">
                    Every publisher aims to benefit from its ad space as much as
                    possible. We provide the right technology that helps
                    publishers to increase their ad revenue and opens the door
                    to a world full of new buyers by combining several ad
                    bidding platforms into one. Our ad tech lets multiple demand
                    sources bid on the same ad space at the same time,
                    increasing the competition and allowing publishers to sell
                    at the highest possible rate. Keep your company up with a
                    dynamic ad environment and make the most revenue out of it.
                    Join us today.
                  </p>
                  {/* <p className="mt-4">Solutions We Offer</p>
                  <ul className="ml-8">
                    <li className="list-disc">Header Bidding</li>
                  </ul> */}
                </div>
                {/* <div className="flex justify-end">
                  <Link
                    href="/services/advert-technology/case-studies"
                    passHref
                  >
                    <button className="mt-4 border-2 border-purple-400 text-purple-400 px-6 py-2 rounded-full hover:bg-purple-400 hover:text-white">
                      Case Studies
                    </button>
                  </Link>
                </div> */}
              </div>
            ) : null}

            {tab === 0 || tab === 4 ? (
              <div className="py-8">
                <p className="lg:text-4xl md:text-3xl text-2xl font-semibold">
                  Digital Media Advertising
                </p>
                <div className="my-8 w-full h-96 relative">
                  <Image
                    src={advertising}
                    alt="Digital Media Advertising"
                    objectFit="contain"
                    layout="fill"
                  />
                </div>
                <p className="md:text-base text-xs">
                  We partner with top online platforms to deploy various ad
                  formats, optimise and measure engagement.
                </p>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </div>
  )
}

export default Services
