import Head from "next/head"
import Image from "next/image"
import { useState } from "react"
import { FiChevronDown } from "react-icons/fi"
import standard from "../../../../public/The-Standard.png"
import channels from "../../../../public/Channels.png"

const CaseStudy = () => {
  const [tab, setTab] = useState(0)
  return (
    <div>
      <Head>
        <title> Case Studies | TKBrown</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/logo_transparent_background_small.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/logo_transparent_background_small.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/logo_transparent_background_small.png"
        />
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>

      <header className="relative h-screen bg-purple-900">
        {/**jumbo */}
        <div className="px-8 py-40 h-full font-bold text-white text-center flex items-center justify-center font-oswald">
          <span className="xl:text-9xl md:text-7xl text-3xl font-semibold">
            CASE STUDIES
          </span>
        </div>

        {/**down button */}
        <div className="absolute bottom-6 left-1/2 text-white">
          <FiChevronDown
            size={24}
            onClick={() => {
              const height = document.documentElement.clientHeight - 125
              window.scrollTo({
                top: height,
                left: 0,
                behavior: "smooth",
              })
            }}
            className="cursor-pointer hover:-translate-y-1/4 transform transition"
          />
        </div>
      </header>

      {/**case studies */}
      <div className="py-24 xl:px-32 md:px-16 px-8 flex lg:flex-row flex-col">
        <div className="lg:w-1/4 md:w-1/2 w-full lg:mb-0 mb-8 px-4">
          <div className="px-8 py-8 rounded-2xl border border-gray-50 shadow-outline shadow-gray-200 divide-y-2 divide-gray-100 space-y-4">
            <p className="text-xl font-semibold">CASE STUDIES</p>
            <div className="space-y-4 py-4 flex flex-col">
              <span
                className="cursor-pointer hover:text-purple-400 text-sm"
                onClick={() => setTab(0)}
              >
                All Case Studies
              </span>
              <span
                className="cursor-pointer hover:text-purple-400 text-sm"
                onClick={() => setTab(1)}
              >
                Standard Media
              </span>
              <span
                className="cursor-pointer hover:text-purple-400 text-sm"
                onClick={() => setTab(2)}
              >
                Channels
              </span>
              <span
                className="cursor-pointer hover:text-purple-400 text-sm"
                onClick={() => setTab(3)}
              >
                Punch
              </span>
            </div>
          </div>
        </div>

        <div className="lg:w-3/4 w-full px-4">
          <div className="px-8 rounded-2xl border border-gray-50 shadow-outline shadow-gray-200 divide-y-2 divide-gray-200">
            {tab === 0 || tab === 1 ? (
              <div className="py-8">
                <p className="lg:text-4xl md:text-3xl text-2xl font-semibold">
                  The Standard Media
                </p>
                <div className="my-8 w-full h-48 relative">
                  <Image
                    src={standard}
                    alt="The Standard Media"
                    objectFit="contain"
                    layout="fill"
                  />
                </div>

                {/**intro */}
                <div className="my-4">
                  <p className="font-semibold italic">
                    How TKBrown gained the client&apos;s trust and managed to
                    increase ad revenue by 20%
                  </p>
                </div>

                {/**about */}
                <div className="my-4">
                  <p className="font-semibold mb-2 text-lg">
                    About Standard Media
                  </p>
                  <p className="md:text-base text-xs">
                    Standard Media is one of the top news publishing websites in
                    Africa. They offer a large collection of news update across
                    various demography and sectors.
                  </p>
                </div>

                {/**challenges */}
                <div className="my-4">
                  <p className="">
                    <span className="font-semibold text-lg">
                      The Challenge:
                    </span>{" "}
                    Find the right ad formats and gain the client&apos;s trust
                    by filling out empty spaces with ads on the website.
                  </p>
                  <p className="mt-2">
                    Since the client&apos;s website is custom-built, it was
                    quite challenging to decide which ad formats would bring the
                    most revenue.
                  </p>
                  <p className="mt-2">
                    Our client previously was using Google AdSense. So, at
                    first, it was important to gain trust and prove that if they
                    fill out empty ad placements and use our header bidding
                    technology, their ad revenue will increase.
                  </p>
                </div>

                {/**solution */}
                <div className="my-4">
                  <p>
                    <span className="text-lg font-semibold">Our Solution:</span>{" "}
                    Placing sticky sidebar ads and a desktop billboard ad on the
                    top
                  </p>
                </div>

                {/**results */}
                <div className="my-4">
                  <p>
                    <span className="font-semibold text-lg">The Results:</span>{" "}
                    20% ad revenue uplift and premium quality ads
                  </p>
                  <p className="mt-4">
                    <span className="italic">
                      &quot;Thanks to our Chrome extension, I can simply follow
                      up and understand which ad placements work better for my
                      site and which are the ones that bring me the most money
                      in real-time.&quot;
                    </span>{" "}
                    - Abayo, Online Advertising Executive
                  </p>
                </div>
              </div>
            ) : null}

            {tab === 0 || tab === 2 ? (
              <div className="py-8">
                <p className="lg:text-4xl md:text-3xl text-2xl font-semibold">
                  Channels
                </p>
                <div className="my-8 w-full h-24 relative">
                  <Image
                    src={channels}
                    alt="Channels"
                    objectFit="contain"
                    layout="fill"
                  />
                </div>

                {/**intro */}
                <div className="my-4">
                  <p className="font-semibold italic">
                    How TKBrown gained the client&apos;s trust and managed to
                    increase ad revenue by almost 200%
                  </p>
                </div>

                {/**about */}
                <div className="my-4">
                  <p className="font-semibold mb-2 text-lg">About Channels</p>
                  <p className="md:text-base text-xs">
                    Channels is one of the top news publishing websites in
                    Africa. They offer a large collection of news update across
                    various demography and sectors.
                  </p>
                </div>

                {/**challenges */}
                <div className="my-4">
                  <p className="">
                    <span className="font-semibold text-lg">
                      The Challenge:
                    </span>{" "}
                    Eliminate client doubts regarding monetization and provide
                    the right ad units
                  </p>
                  <p className="mt-2">
                    For Channels it is vital to educate potential and current
                    clients about monetization benefits. Website monetization
                    isn&apos;t only about optimizing publishers&apos; ad
                    revenue, but also technical expertise in the field, right ad
                    placements, clients&apos; trust, time, and cost-efficiency.
                  </p>
                </div>

                {/**solution */}
                <div className="my-4">
                  <p>
                    <span className="text-lg font-semibold">Our Solution:</span>{" "}
                    Individual account manager and easy implementation process
                  </p>
                  <div className="mt-2">
                    Channels&apos;s main goal for TKBrown was to provide
                    excellent support and personalized monetization solution.
                    Thanks to our team of professionals, we managed to make the
                    implementation process as simple as possible, so the
                    publisher&apos;s ad revenue could start to increase rapidly.
                  </div>
                </div>

                {/**results */}
                <div className="my-4">
                  <p>
                    <span className="font-semibold text-lg">The Results:</span>{" "}
                    Almost 200% ad revenue uplift and premium quality ads
                  </p>
                  {/* <p className="mt-4">
                    <span className="italic">
                      &quot;Thanks to our Chrome extension, I can simply follow
                      up and understand which ad placements work better for my
                      site and which are the ones that bring me the most money
                      in real-time.&quot;
                    </span>{" "}
                    - Abayo, Online Advertising Executive
                  </p> */}
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </div>
  )
}

export default CaseStudy
