import Head from "next/head"
import Image from "next/image"
import Navbar from "../components/Navbar"
import { FiChevronDown, FiChevronUp } from "react-icons/fi"
import { FaUsers, FaDesktop, FaBullhorn, FaTrophy } from "react-icons/fa"
import box4 from "../public/p3-3.png"
import box5 from "../public/Revlon.jpg"
import box6 from "../public/about-roos.png"
import box8 from "../public/Lanre-Dasilva-Ajayi_01.jpg"

const About = () => {
  return (
    <div className="font-hind min-h-screen">
      <Head>
        <title>About | TK Brown</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="relative h-screen bg-aboutCloud bg-cover bg-right-top before:absolute before:top-0 before:right-0 before:bottom-0 before:left-0 before:bg-opa">
        <Navbar page="about" />
        <div className="h-full w-full flex justify-center items-center text-white relative font-oswald">
          <span className="text-[125px] font-semibold">ABOUT US</span>
        </div>
        <div className="absolute bottom-6 left-1/2 text-white">
          <a href="#section-2">
            <FiChevronDown size={24} />
          </a>
        </div>
      </header>

      <main id="section-2" className="min-h-screen flex flex-wrap relative">
        <div className="relative w-1/3 h-[420px] flex flex-col items-center justify-center bg-swirl bg-cover bg-center space-y-6">
          <div className="bg-black rounded-full p-6 text-white">
            <FaUsers size={48} />
          </div>
          <span className="font-oswald text-4xl font-semibold">ABOUT US</span>
          <span className="font-hind px-8 text-dark text-center">
            Brand Strategy & Communications agency offering customised services
            allowing brands focus on the core of the business.
          </span>
        </div>

        <div className="relative w-1/3 h-[420px] bg-gray-100 flex items-center justify-center">
          <span className="font-playfair text-6xl">TK Brown</span>
        </div>

        <div className="relative w-1/3 h-[420px] flex flex-col items-center justify-center bg-swirl bg-cover bg-center space-y-6">
          <div className="bg-black rounded-full p-6 text-white">
            <FaDesktop size={48} />
          </div>
          <span className="font-oswald text-4xl font-semibold">WHERE</span>
          <span className="font-hind px-8 text-dark text-center">
            TSC Agency is based in Lagos, Nigeria.
          </span>
        </div>

        <div className="relative w-1/3 h-[420px]">
          <Image src={box4} alt="" objectFit="cover" layout="fill" />
        </div>

        <div className="relative w-1/3 h-[420px]">
          <Image src={box5} alt="" objectFit="cover" layout="fill" />
        </div>

        <div className="relative w-1/3 h-[420px]">
          <Image
            src={box6}
            alt=""
            objectFit="cover"
            layout="fill"
            objectPosition="top"
          />
        </div>

        <div className="relative w-1/3 h-[420px] flex flex-col items-center justify-center bg-swirl bg-cover bg-center space-y-6">
          <div className="bg-black rounded-full p-6 text-white">
            <FaBullhorn size={48} />
          </div>
          <span className="font-oswald text-4xl font-semibold">WHY US?</span>
          <span className="font-hind px-8 text-dark text-center">
            Our goal at TSC Agency is simple. Create a buzz about our client and
            their brand. We do this by strategic planning and creating packages
            that are most suitable to you. From concept to execution, TSC Agency
            will work hard to tell your brand&apos;s story.
          </span>
        </div>

        <div className="relative w-1/3 h-[420px]">
          <Image
            src={box8}
            alt=""
            objectFit="cover"
            layout="fill"
            objectPosition="top"
          />
        </div>

        <div className="relative w-1/3 h-[420px] flex flex-col items-center justify-center bg-swirl bg-cover bg-center space-y-6">
          <div className="bg-black rounded-full p-6 text-white">
            <FaTrophy size={48} />
          </div>
          <span className="font-oswald text-4xl font-semibold">AIM</span>
          <span className="font-hind px-8 text-dark text-center">
            Our primary aim at TSC Agency is to allow brands focus on the core
            of their business while we present their brand in the best possible
            light.
          </span>
        </div>

        <div className="absolute bottom-0 right-2 p-0.5 text-white bg-black">
          <a href="#">
            <FiChevronUp size={24} />
          </a>
        </div>
      </main>
    </div>
  )
}

export default About
