import { useState } from "react"
import Head from "next/head"
import Image from "next/image"
import Navbar from "../components/Navbar"
import { FiChevronDown } from "react-icons/fi"
import dms from "../public/digital-media-strategy.webp"
import content from "../public/content-marketing.webp"
import digitalSales from "../public/digital-media-sales.webp"
import adEngineering from "../public/ad-engineering.webp"

const Services = () => {
  const [tab, setTab] = useState(0)
  return (
    <div>
      <Head>
        <title>Services | TKBrown</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="relative h-screen bg-purple-900">
        {/**navbar */}
        <Navbar />

        {/**jumbo */}
        <div className="px-8 py-40 h-full font-bold text-white text-center flex items-center justify-center font-oswald">
          <span className="xl:text-9xl md:text-7xl text-3xl font-semibold">
            SERVICES
          </span>
        </div>

        {/**down button */}
        <div className="absolute bottom-6 left-1/2 text-white">
          <FiChevronDown
            size={24}
            onClick={() => {
              const height = document.documentElement.clientHeight - 125
              window.scrollTo({
                top: height,
                left: 0,
                behavior: "smooth",
              })
            }}
            className="cursor-pointer hover:-translate-y-1 transform transition"
          />
        </div>
      </header>

      {/**all services */}
      <div className="py-24 px-32 flex">
        <div className="w-1/4 px-4">
          <div className="px-8 py-8 rounded-2xl border border-gray-50 shadow-outline shadow-gray-200 divide-y-2 divide-gray-100 space-y-4">
            <p className="text-xl font-semibold">OUR SERVICES</p>
            <div className="space-y-4 py-4 flex flex-col">
              <span
                className="cursor-pointer hover:text-purple-400 text-sm"
                onClick={() => setTab(0)}
              >
                All Services
              </span>
              <span
                className="cursor-pointer hover:text-purple-400 text-sm"
                onClick={() => setTab(1)}
              >
                Digital Media Strategy
              </span>
              <span
                className="cursor-pointer hover:text-purple-400 text-sm"
                onClick={() => setTab(2)}
              >
                Content Marketing
              </span>
              <span
                className="cursor-pointer hover:text-purple-400 text-sm"
                onClick={() => setTab(3)}
              >
                Digital Media Sales
              </span>
              <span
                className="cursor-pointer hover:text-purple-400 text-sm"
                onClick={() => setTab(4)}
              >
                Ad Engineering
              </span>
            </div>
          </div>
        </div>

        <div className="w-3/4 px-4">
          <div className="px-8 rounded-2xl border border-gray-50 shadow-outline shadow-gray-200 divide-y-2 divide-gray-200">
            {tab === 0 || tab === 1 ? (
              <div className="py-8">
                <p className="text-4xl font-semibold">Digital Media Strategy</p>
                <div className="my-8 w-full h-96 relative">
                  <Image
                    src={dms}
                    alt="Digital Media Strategy"
                    objectFit="contain"
                    layout="fill"
                  />
                </div>
                <p className="text-sm">
                  The internet is a global village and we understand perfectly
                  how to walk our way around it.As experts, we can help you
                  define/recommend the best digital strategy for business growth
                  and expansion. We understand the demography of popular
                  platforms and understand which combination will yield maximum
                  impact and ensure a positive ROI. Patronage is built on Ad
                  visibility, on trust, and the ability to create a relationship
                  with your clients and that is why we are here- we can help
                  you!
                </p>
              </div>
            ) : null}

            {tab === 0 || tab === 2 ? (
              <div className="py-8">
                <p className="text-4xl font-semibold">Content Marketing</p>
                <div className="my-8 w-full h-96 relative">
                  <Image
                    src={content}
                    alt="Content Marketing"
                    objectFit="contain"
                    layout="fill"
                  />
                </div>
                <p className="text-sm">
                  If Content is fire and social media is gasoline, then Digital
                  Tribe owns the refinery. We have the platforms and technical
                  expertise to create and deploy banners, images, GIF,Rich Media
                  and videos. We also monitor interactions,impressions,and
                  clicks generated on advertised content. We run Africa’s
                  largest mobile network; plugging into well over 50 platforms
                  that allow all types of ad formats to be displayed. With the
                  growth of smartphones and internet usage, mobile platforms
                  create a fertile ground for content marketing.
                </p>
              </div>
            ) : null}

            {tab === 0 || tab === 3 ? (
              <div className="py-8">
                <p className="text-4xl font-semibold">Digital Media Sales</p>
                <div className="my-8 w-full h-96 relative">
                  <Image
                    src={digitalSales}
                    alt="Digital Media Sales"
                    objectFit="contain"
                    layout="fill"
                  />
                </div>
                <p className="text-sm">
                  We sell advertising space on popular online platforms such as
                  websites, blogs, and digital properties. We help brands deploy
                  several Ad formats, measure click metrics, and engagement
                  measurement. Using automated technologies and viral platforms,
                  we help brands drive their key messages to the right target
                  audience.
                </p>
              </div>
            ) : null}

            {tab === 0 || tab === 4 ? (
              <div className="py-8">
                <p className="text-4xl font-semibold">Ad Engineering</p>
                <div className="my-8 w-full h-96 relative">
                  <Image
                    src={adEngineering}
                    alt="Ad Engineering"
                    objectFit="contain"
                    layout="fill"
                  />
                </div>
                <p className="text-sm">
                  The integration of technology in business has changed what
                  used to be a level playing field. Advertising has grown beyond
                  paying Facebook, Instagram, or even google for sponsored Ads.
                  Traditional advertising is good but the reach of digital
                  advertising is higher and measurable. Brands and business
                  owners must take their products and services to the digital
                  space of their clients and customers. Our Advert engineering
                  service allows clients use our dedicated Demand Side Platform
                  to deploy Ads on websites with huge traffic. Our clients can
                  target and retarget prospective customers using various Ad
                  segments:
                </p>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </div>
  )
}

export default Services
